[client]
showSidebarNavigation = false
[theme]
#base="light"
primaryColor ='#84563c'
backgroundColor ='#FDF6EC'
secondaryBackgroundColor ='#FFFFFF'
textColor ='#562400'
#textColor ='#00CED4'
#'#562400'
#font ='sans serif'
