[client]
showSidebarNavigation = false
[theme]
#base="light"
primaryColor ='#FFE5C2'
backgroundColor ='#FDF6EC'
secondaryBackgroundColor ='#FFFFFF'
textColor ='#7F3300'
#textColor ='#00CED4'
#'#562400'
#font ='sans serif'
