[client]
showSidebarNavigation = false
[theme]
#base="light"
primaryColor ='FF8B00'
backgroundColor ='#FDF6EC'
secondaryBackgroundColor ='#FFFFFF'
textColor ='#000000'
#textColor ='#00CED4'
#'#562400'
#font ='sans serif'
